---

- name: Check if gradle 3.1 is already installed
  stat: 
    path: "{{home_dir}}/.sdkman/candidates/gradle/3.1/"
  register: gradle31_dir

- name: Check if gradle 2.9 is already installed
  stat: 
    path: "{{home_dir}}/.sdkman/candidates/gradle/2.9/"
  register: gradle29_dir

- name: Check if maven is already installed
  stat: 
    path: "{{home_dir}}/.sdkman/candidates/maven/"
  register: maven_dir

- name: Check if springboot cli is already installed
  stat: 
    path: "{{home_dir}}/.sdkman/candidates/springboot/"
  register: springbootcli_dir

- name: Installing gradle 3.1
  when: gradle31_dir.stat.isdir is not defined
  command: bash -lc "sdk install gradle 3.1"
  become_user: vagrant

- name: Installing gradle 2.9
  when: gradle29_dir.stat.isdir is not defined
  command: bash -lc "sdk install gradle 2.9"
  become_user: vagrant

- name: Installing maven
  when: maven_dir.stat.isdir is not defined
  command: bash -lc "sdk install maven"
  become_user: vagrant

- name: Installing spring boot cli
  when: springbootcli_dir.stat.isdir is not defined
  command: bash -lc "sdk install springboot"
  become_user: vagrant
