---

- name: Default configurations
  hosts: all
  become: true
  become_user: root
  roles:
    - so-config
    - so-tools
    - docker
    - docker-compose
  
- name: NODEJS env configs
  hosts: node
  become: true
  become_user: root
  vars:
    env: nodejs
  roles:
    - hostname
    - nodejs

- name: SERVICES env configs
  hosts: services
  become: true
  become_user: root
  vars:
    env: services
  roles:
    - hostname
    - services
    - nginx
    - terraform

- name: RUBY env configs
  hosts: ruby
  become: true
  become_user: root
  vars:
    env: ruby
  roles:
    - hostname
    - rvm
    - nodejs

- name: JAVA env configs
  hosts: java
  become: true
  become_user: root
  vars:
    env: java
  roles:
    - hostname
    - java
    - sdkman
    - xserver

- name: ELIXIR env configs
  hosts: elixir
  become: true
  become_user: root
  vars:
    env: elixir
  roles:
    - hostname
    - elixir

- name: CRYSTAL env configs
  hosts: crystal
  become: true
  become_user: root
  vars: 
    env: crystal
  roles:
    - hostname
    - crystal