---

- name: Default configurations
  hosts: all
  become: true
  become_user: root
  vars:
    workspace_dir: /home/vagrant/projects
    home_dir: /home/vagrant
    default_user: vagrant
  roles:
    - so-config
    - git
  
- name: NODEJS env configs
  hosts: node
  become: true
  become_user: root
  vars:
    env: nodejs
    node_version: 6.1.0
    nodejs_version: 6.x
    workspace_dir: /home/vagrant/projects
    home_dir: /home/vagrant
    default_user: vagrant
  roles:
    - hostname
    - nodejs
    - clones

- name: SERVICES env configs
  hosts: services
  become: true
  become_user: root
  vars:
    env: services
    workspace_dir: /home/vagrant/services
  roles:
    - hostname
    - docker
    - docker-compose

- name: RUBY env configs
  hosts: ruby
  become: true
  become_user: root
  vars:
    env: ruby
  roles:
    - hostname
    - rvm
    - nodejs
    - clones