---

- name: Default configurations
  hosts: all
  become: true
  become_user: root
  roles:
    - so-config
    - git
  
- name: NODEJS env configs
  hosts: node
  become: true
  become_user: root
  vars:
    env: nodejs
  roles:
    - hostname
    - nodejs
    - clones

- name: SERVICES env configs
  hosts: services
  become: true
  become_user: root
  vars:
    env: services
  roles:
    - hostname
    - docker
    - docker-compose

- name: RUBY env configs
  hosts: ruby
  become: true
  become_user: root
  vars:
    env: ruby
  roles:
    - hostname
    - rvm
    - nodejs
    - clones

- name: JAVA env configs
  hosts: java
  become: true
  become_user: root
  vars:
    env: java
  roles:
    - hostname
    - java
    - sdk
    - clones