---

- name: Install ruby 2.3.0
  command: "{{home_dir}}/.rvm/bin/rvm install 2.3.0"
  become_user: "{{default_user}}"

- name: Use Ruby 2.3.0 as default
  command: 'bash -lc "rvm use 2.3.0 --default"'
  become_user: "{{default_user}}"