---

- name: Install dependencies for XServer
  apt: name={{item}} state=present
  with_items:
    - xfce4 
    - virtualbox-guest-dkms 
    - virtualbox-guest-utils 
    - virtualbox-guest-x11

- name: Install theme
  apt: name={{item}} state=present
  with_items:
    - gnome-icon-theme-full 
    - tango-icon-theme

- name: Able to start XFCE4 as non privileged user
  lineinfile:
    dest: "/etc/X11/Xwrapper.config"
    regexp: ^allowed_users=
    line: allowed_users=anybody