---

- name: Check if eclipse is already installed
  when: env == 'java'
  stat: 
    path: "/opt/eclipse"
  register: eclipse_dir

- name: Download eclipse
  when: env == 'java' and (eclipse_dir.stat.isdir is not defined)
  get_url:
    url: http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz
    dest: "/opt/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz"
    mode: 0755

- name: Unpack eclipse
  when: env == 'java' and (eclipse_dir.stat.isdir is not defined)
  unarchive:
    src: /opt/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz
    dest: /opt
    remote_src: True

- name: Remove eclipse tar.gz
  when: env == 'java' and (eclipse_dir.stat.isdir is not defined)
  file: 
    path: /opt/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz
    state: absent