---

- name: add Kubernetes apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce

- name: add vagrant to docker group
  user:
    name: "{{default_user}}"
    groups: docker
    append: yes
